const insults = {
  INTJ: [
"You planned your life but forgot to enjoy it.",
"You treat emotions like bugs to be fixed.",
"You think you're mysterious, you're just unavailable.",
"You optimize everything except your social life.",
"You trust logic more than people and it shows.",
"You plan conversations like strategy games.",
"You think you're 10 steps ahead but no one's playing.",
"You avoid small talk like it's toxic waste.",
"You analyze feelings instead of feeling them.",
"You think independence is a personality.",
"You call it vision, others call it isolation.",
"You make plans nobody asked for.",
"You treat life like a simulation you forgot to enjoy.",
"You prefer control over connection.",
"You overthink everything into nothing.",
"You assume you're right before listening.",
"You think you're deep but you're just distant.",
"You schedule life like a meeting.",
"You expect efficiency from emotions.",
"You act like vulnerability is a weakness.",
"You see flaws in everything including people.",
"You think being alone equals being superior.",
"You trust your mind more than reality.",
"You want perfection but tolerate loneliness.",
"You talk less but judge more.",
"You value intelligence but ignore empathy.",
"You treat people like variables.",
"You think you're hard to understand on purpose.",
"You isolate yourself then complain about it.",
"You confuse control with peace."
],
"INTP": [
  "You don’t procrastinate, you just let ideas marinate forever.",
  "You’ve planned your future perfectly, just never started it.",
  "You treat deadlines like suggestions from a less intelligent being.",
  "You can explain quantum physics but not your own sleep schedule.",
  "You start thinking and forget to come back.",
  "Your brain has 100 tabs open and 98 of them are useless theories.",
  "You love solving problems, just not your own.",
  "You disappear mid-conversation like a background process.",
  "You don’t ghost people, you just forget they exist temporarily.",
  "You analyze everything except your own bad habits.",
  "You’d win debates if you cared enough to finish your sentences.",
  "You’re intellectually intimidating but practically unavailable.",
  "You have elite thoughts and zero execution.",
  "You don’t overthink, you overbuild problems.",
  "You’d rather understand life than actually live it.",
  "You optimize systems that don’t matter and ignore ones that do.",
  "You have the potential to be great, consistently unused.",
  "You question everything except your own procrastination.",
  "You treat real life like a theory you’ll test later.",
  "You can focus for 10 hours or not at all, no in between.",
  "You reinvent solutions instead of finishing tasks.",
  "You get bored right before success.",
  "You’re allergic to routine but addicted to ideas.",
  "You think deeply and act rarely.",
  "You could change the world but got distracted halfway.",
  "You love complexity because simplicity requires action.",
  "You debug thoughts better than your own life.",
  "You’re a genius in theory and a mess in practice.",
  "You wait for the perfect moment that never arrives.",
  "You collect ideas like trophies and finish none of them."
],"INFP": [
  "You don’t live in reality, you visit it occasionally.",
  "You feel everything deeply except the need to reply on time.",
  "You romanticize your problems instead of solving them.",
  "You’ve created 10 alternate lives in your head and none in real life.",
  "You cry over fictional characters more than real responsibilities.",
  "You want to change the world but get overwhelmed changing your routine.",
  "You disappear emotionally even when you’re physically present.",
  "You trust vibes more than logic and then wonder what went wrong.",
  "You start journaling your feelings instead of fixing the situation.",
  "You avoid conflict so hard you create bigger problems.",
  "You’re the main character in a story that has no plot progression.",
  "You wait for the perfect feeling before doing anything.",
  "You give great advice you never follow.",
  "You overthink texts like they’re life-changing decisions.",
  "You want deep connections but fear basic communication.",
  "You get attached to potential instead of reality.",
  "You feel misunderstood but refuse to explain yourself.",
  "You escape into music instead of dealing with your life.",
  "You turn minor inconveniences into emotional story arcs.",
  "You want peace but avoid the actions that create it.",
  "You live in your head and rent is free.",
  "You forgive people too easily and regret it later.",
  "You dream big but act small.",
  "You need alone time after basic human interaction.",
  "You confuse being sensitive with being helpless.",
  "You expect people to just ‘get you’ without effort.",
  "You avoid decisions until they make themselves.",
  "You feel everything intensely and act on nothing.",
  "You’re emotionally deep but practically lost.",
  "You write imaginary conversations instead of having real ones."
],"ISTP": [
  "You fix machines better than you fix your own life.",
  "You disappear for hours and call it ‘peace’.",
  "You hate drama but somehow attract it anyway.",
  "You’d rather take something apart than talk about your feelings.",
  "You respond to texts like it costs money.",
  "You ghost people just to avoid explaining yourself.",
  "You’re emotionally unavailable but somehow still confusing.",
  "You learn by doing but forget to think ahead.",
  "You hate rules until consequences show up.",
  "You’re calm under pressure because you ignore problems until they explode.",
  "You’d rather struggle alone than ask for help.",
  "You act first and think later, sometimes never.",
  "You avoid commitment like it’s a system error.",
  "You’re independent to the point of isolation.",
  "You fix things fast but break plans even faster.",
  "You don’t overthink, you under-explain.",
  "You hate being told what to do but don’t plan anything yourself.",
  "You’re chill until responsibility shows up.",
  "You live in the moment because planning feels illegal.",
  "You solve practical problems but ignore emotional ones.",
  "You keep things simple except your communication.",
  "You vanish mid-conversation like a glitch.",
  "You don’t like people but somehow people like you.",
  "You avoid drama by creating distance, not solutions.",
  "You’re low maintenance but also low communication.",
  "You act like you don’t care until it’s too late.",
  "You prefer action over words because words expose you.",
  "You handle tools better than relationships.",
  "You stay quiet and expect people to understand everything.",
  "You’re efficient, detached, and occasionally missing."
],
 ENFP: [
"You start everything and finish nothing.",
"You get excited faster than you commit.",
"Your attention span has trust issues.",
"You fall in love with ideas, not reality.",
"You call chaos 'energy'.",
"You make plans you forget immediately.",
"You chase passion but avoid discipline.",
"You talk big, act small.",
"You rely on vibes for decision making.",
"You get bored of your own dreams.",
"You start projects like hobbies.",
"You live in potential, not results.",
"You confuse excitement with progress.",
"You abandon things mid-way like it's normal.",
"You romanticize effort, not outcomes.",
"You overpromise and underdeliver.",
"You avoid structure like it's toxic.",
"You jump between ideas like tabs.",
"You think motivation replaces consistency.",
"You start strong, end invisible.",
"You rely on feelings for logic.",
"You hate routine but need it.",
"You avoid commitment like a sport.",
"You think spontaneity solves everything.",
"You distract yourself from responsibility.",
"You have ideas, not execution.",
"You run from boredom into chaos.",
"You want freedom but avoid discipline.",
"You talk about dreams more than building them.",
"You confuse being busy with being productive."
],
ENTP: [
"You argue even when you're wrong.",
"You debate for fun, not truth.",
"You create chaos for entertainment.",
"You think you're clever, you're just annoying.",
"You interrupt people like it's your job.",
"You start arguments you can't finish.",
"You value winning over being right.",
"You confuse intelligence with arrogance.",
"You talk more than you think.",
"You enjoy conflict too much.",
"You turn discussions into competitions.",
"You don't listen, you prepare replies.",
"You argue both sides and believe neither.",
"You push boundaries just to see reactions.",
"You treat conversations like debates.",
"You think controversy equals intelligence.",
"You dominate conversations without substance.",
"You provoke people for fun.",
"You confuse boldness with depth.",
"You debate even when it's unnecessary.",
"You love ideas but avoid commitment.",
"You derail conversations easily.",
"You think fast but shallow.",
"You chase stimulation, not meaning.",
"You challenge everything except yourself.",
"You argue to win, not understand.",
"You enjoy being difficult.",
"You think you're unique, you're predictable.",
"You escalate conversations for no reason.",
"You confuse noise with intelligence."
],
ENTP: [
"You argue even when you're wrong.",
"You debate for fun, not truth.",
"You create chaos for entertainment.",
"You think you're clever, you're just annoying.",
"You interrupt people like it's your job.",
"You start arguments you can't finish.",
"You value winning over being right.",
"You confuse intelligence with arrogance.",
"You talk more than you think.",
"You enjoy conflict too much.",
"You turn discussions into competitions.",
"You don't listen, you prepare replies.",
"You argue both sides and believe neither.",
"You push boundaries just to see reactions.",
"You treat conversations like debates.",
"You think controversy equals intelligence.",
"You dominate conversations without substance.",
"You provoke people for fun.",
"You confuse boldness with depth.",
"You debate even when it's unnecessary.",
"You love ideas but avoid commitment.",
"You derail conversations easily.",
"You think fast but shallow.",
"You chase stimulation, not meaning.",
"You challenge everything except yourself.",
"You argue to win, not understand.",
"You enjoy being difficult.",
"You think you're unique, you're predictable.",
"You escalate conversations for no reason.",
"You confuse noise with intelligence."
],
INFJ: [
"You understand everyone except yourself.",
"You give advice you don't follow.",
"You overthink emotions until they disappear.",
"You feel deeply but express nothing.",
"You act mysterious but you're just confused.",
"You absorb others' problems like a sponge.",
"You avoid conflict but suffer internally.",
"You want deep connections but isolate yourself.",
"You overanalyze conversations from days ago.",
"You expect people to understand you without explaining.",
"You feel everything but say nothing.",
"You carry emotional weight no one gave you.",
"You confuse intuition with assumption.",
"You struggle between logic and emotion constantly.",
"You want meaning but avoid clarity.",
"You help others while ignoring yourself.",
"You think you're complex but you're overwhelmed.",
"You romanticize your struggles.",
"You search for purpose but stay stuck.",
"You overthink decisions into regret.",
"You feel misunderstood but don't communicate.",
"You analyze people more than yourself.",
"You avoid confrontation but build resentment.",
"You expect emotional depth from everyone.",
"You reflect too much, act too little.",
"You think you're guiding others while lost yourself.",
"You internalize everything unnecessarily.",
"You struggle to balance thought and action.",
"You want connection but fear vulnerability.",
"You live in emotions more than reality."
],
INFJ: [
"You understand everyone except yourself.",
"You give advice you don't follow.",
"You overthink emotions until they disappear.",
"You feel deeply but express nothing.",
"You act mysterious but you're just confused.",
"You absorb others' problems like a sponge.",
"You avoid conflict but suffer internally.",
"You want deep connections but isolate yourself.",
"You overanalyze conversations from days ago.",
"You expect people to understand you without explaining.",
"You feel everything but say nothing.",
"You carry emotional weight no one gave you.",
"You confuse intuition with assumption.",
"You struggle between logic and emotion constantly.",
"You want meaning but avoid clarity.",
"You help others while ignoring yourself.",
"You think you're complex but you're overwhelmed.",
"You romanticize your struggles.",
"You search for purpose but stay stuck.",
"You overthink decisions into regret.",
"You feel misunderstood but don't communicate.",
"You analyze people more than yourself.",
"You avoid confrontation but build resentment.",
"You expect emotional depth from everyone.",
"You reflect too much, act too little.",
"You think you're guiding others while lost yourself.",
"You internalize everything unnecessarily.",
"You struggle to balance thought and action.",
"You want connection but fear vulnerability.",
"You live in emotions more than reality."
],
ENFJ: [
"You help everyone except yourself.",
"You give advice but ignore your own problems.",
"You take responsibility for others' emotions.",
"You try to fix people who didn't ask.",
"You overextend yourself constantly.",
"You confuse helping with controlling.",
"You struggle to set boundaries.",
"You absorb stress from everyone around you.",
"You act strong but feel overwhelmed.",
"You prioritize others over yourself.",
"You take on problems that aren't yours.",
"You want harmony but avoid honesty.",
"You try to please everyone and fail.",
"You think you're guiding but you're exhausted.",
"You sacrifice too much for approval.",
"You struggle to say no.",
"You carry emotional burdens unnecessarily.",
"You expect appreciation that never comes.",
"You overcommit and burn out.",
"You ignore your own needs.",
"You think you're responsible for happiness.",
"You help others to feel needed.",
"You avoid conflict but create stress.",
"You expect people to change because you care.",
"You give energy you don't have.",
"You struggle to balance giving and receiving.",
"You act selfless but feel drained.",
"You need validation for your efforts.",
"You help people who won't help themselves.",
"You forget yourself while fixing others."
],
ENFJ: [
"You help everyone except yourself.",
"You give advice but ignore your own problems.",
"You take responsibility for others' emotions.",
"You try to fix people who didn't ask.",
"You overextend yourself constantly.",
"You confuse helping with controlling.",
"You struggle to set boundaries.",
"You absorb stress from everyone around you.",
"You act strong but feel overwhelmed.",
"You prioritize others over yourself.",
"You take on problems that aren't yours.",
"You want harmony but avoid honesty.",
"You try to please everyone and fail.",
"You think you're guiding but you're exhausted.",
"You sacrifice too much for approval.",
"You struggle to say no.",
"You carry emotional burdens unnecessarily.",
"You expect appreciation that never comes.",
"You overcommit and burn out.",
"You ignore your own needs.",
"You think you're responsible for happiness.",
"You help others to feel needed.",
"You avoid conflict but create stress.",
"You expect people to change because you care.",
"You give energy you don't have.",
"You struggle to balance giving and receiving.",
"You act selfless but feel drained.",
"You need validation for your efforts.",
"You help people who won't help themselves.",
"You forget yourself while fixing others."
],
ISFJ: [
"You take care of everyone except yourself.",
"You say 'it's fine' when it's not.",
"You avoid conflict at all costs.",
"You carry emotional burdens silently.",
"You prioritize others too much.",
"You struggle to say no.",
"You suppress your own needs.",
"You fear disappointing others.",
"You hold onto past issues.",
"You avoid confrontation entirely.",
"You overthink others' opinions.",
"You sacrifice too much.",
"You stay quiet instead of speaking up.",
"You take responsibility for others.",
"You struggle to express frustration.",
"You avoid upsetting anyone.",
"You internalize stress.",
"You put others before yourself always.",
"You fear change unnecessarily.",
"You stay in uncomfortable situations.",
"You struggle with boundaries.",
"You overcommit to helping others.",
"You hide your true feelings.",
"You fear rejection too much.",
"You accept more than you should.",
"You stay silent when hurt.",
"You avoid standing up for yourself.",
"You struggle to prioritize yourself.",
"You carry guilt unnecessarily.",
"You overvalue harmony."
],
ISTJ: [
"You treat rules like sacred law.",
"You think fun needs permission.",
"You avoid spontaneity like it's dangerous.",
"You follow structure blindly.",
"You prefer routine over excitement.",
"You resist change unnecessarily.",
"You trust rules more than people.",
"You think tradition equals correctness.",
"You avoid risks completely.",
"You prioritize order over flexibility.",
"You struggle with unexpected situations.",
"You prefer control over adaptability.",
"You take things too seriously.",
"You resist new ideas instinctively.",
"You stick to plans even when wrong.",
"You avoid uncertainty at all costs.",
"You value stability over growth.",
"You struggle with creativity.",
"You follow systems without questioning.",
"You avoid breaking routine.",
"You prefer safety over opportunity.",
"You struggle to adapt quickly.",
"You think consistency is everything.",
"You avoid stepping outside comfort.",
"You resist innovation.",
"You prefer known paths only.",
"You struggle with ambiguity.",
"You rely on structure too much.",
"You think rules solve everything.",
"You avoid anything unpredictable."
],
ENTJ: [
"You lead like a boss but no one applied to follow you.",
"You treat people like resources to optimize.",
"You confuse control with leadership.",
"You think efficiency is a personality.",
"You run conversations like meetings.",
"You expect results from people who didn't sign up.",
"You prioritize winning over understanding.",
"You think being right matters more than being liked.",
"You dominate instead of collaborate.",
"You assume leadership automatically.",
"You value productivity over people.",
"You think emotions are inefficiencies.",
"You push people beyond their limits unnecessarily.",
"You confuse authority with respect.",
"You focus on outcomes, ignore impact.",
"You think you're inspiring but you're exhausting.",
"You expect everyone to match your pace.",
"You take control even when it's not needed.",
"You treat life like a business strategy.",
"You value results over relationships.",
"You think pressure builds character always.",
"You struggle to slow down.",
"You ignore emotional consequences.",
"You push yourself and others too hard.",
"You prioritize goals over well-being.",
"You think success excuses behavior.",
"You lead without listening enough.",
"You assume you're always right.",
"You chase success but miss connection.",
"You treat people like stepping stones."
],ESFP: [
"You need attention like it's a subscription.",
"You turn everything into a performance.",
"You avoid serious thoughts like they're bugs.",
"You think vibes solve real problems.",
"You prioritize fun over responsibility.",
"You avoid depth completely.",
"You seek attention constantly.",
"You struggle with focus.",
"You prioritize excitement over logic.",
"You avoid planning.",
"You rely on feelings over thinking.",
"You chase validation.",
"You avoid serious decisions.",
"You prefer entertainment over growth.",
"You struggle with discipline.",
"You avoid responsibility.",
"You focus on the present only.",
"You ignore long-term consequences.",
"You seek approval constantly.",
"You avoid difficult thinking.",
"You prioritize attention.",
"You struggle with consistency.",
"You avoid structure.",
"You prefer fun over logic.",
"You chase excitement.",
"You avoid depth.",
"You rely on validation.",
"You struggle with seriousness.",
"You avoid responsibility.",
"You prioritize enjoyment."
],
ESFJ: [
"You care so much about opinions it's exhausting.",
"You need validation like oxygen.",
"You organize everyone's life except your own.",
"You avoid conflict but create passive stress.",
"You prioritize approval over truth.",
"You struggle to be alone.",
"You rely on others' opinions too much.",
"You want harmony at any cost.",
"You avoid difficult conversations.",
"You overcommit to social expectations.",
"You care more about perception than reality.",
"You struggle with independence.",
"You seek validation constantly.",
"You avoid upsetting anyone.",
"You follow social norms blindly.",
"You prioritize fitting in.",
"You struggle to make decisions alone.",
"You fear disapproval too much.",
"You overvalue group acceptance.",
"You depend on external approval.",
"You struggle with authenticity.",
"You avoid standing out.",
"You follow expectations too closely.",
"You prioritize social harmony over truth.",
"You fear rejection excessively.",
"You avoid being disliked.",
"You depend on reassurance.",
"You struggle with self-validation.",
"You overthink others' opinions.",
"You live for approval."
],
ESTJ: [
"You think being loud makes you right.",
"You run everything like a corporate office.",
"You confuse authority with personality.",
"You don't listen, you command.",
"You expect rules to solve everything.",
"You dominate conversations unnecessarily.",
"You value control over flexibility.",
"You struggle with adapting.",
"You think structure fixes all problems.",
"You ignore emotional context.",
"You expect obedience not discussion.",
"You prioritize rules over logic.",
"You struggle with nuance.",
"You impose order everywhere.",
"You resist alternative approaches.",
"You expect people to follow blindly.",
"You think efficiency is everything.",
"You ignore creative solutions.",
"You prefer control over collaboration.",
"You struggle with flexibility.",
"You push structure onto everything.",
"You dismiss emotional input.",
"You value systems over people.",
"You assume leadership without question.",
"You expect things done your way.",
"You struggle with compromise.",
"You think you're always right.",
"You enforce rules rigidly.",
"You resist change instinctively.",
"You prioritize control over growth."
],
ISFP: [
"You avoid reality like it's optional content.",
"You feel deeply but explain nothing.",
"You make decisions based on vibes only.",
"You avoid planning like it's stressful.",
"You disappear emotionally mid-conversation.",
"You prefer feelings over logic.",
"You avoid responsibility quietly.",
"You struggle with consistency.",
"You follow moods over discipline.",
"You avoid structure completely.",
"You escape pressure instead of facing it.",
"You rely on feelings for decisions.",
"You struggle with long-term focus.",
"You avoid difficult situations.",
"You act impulsively without thinking.",
"You prefer comfort over growth.",
"You avoid commitments.",
"You struggle with planning ahead.",
"You rely on emotions over logic.",
"You avoid challenges quietly.",
"You prefer easy paths.",
"You struggle with discipline.",
"You avoid confrontation.",
"You follow instincts blindly.",
"You avoid responsibility.",
"You struggle with direction.",
"You prefer short-term comfort.",
"You avoid structured environments.",
"You rely on emotions for everything.",
"You resist planning."
],
ISFP: [
"You avoid reality like it's optional content.",
"You feel deeply but explain nothing.",
"You make decisions based on vibes only.",
"You avoid planning like it's stressful.",
"You disappear emotionally mid-conversation.",
"You prefer feelings over logic.",
"You avoid responsibility quietly.",
"You struggle with consistency.",
"You follow moods over discipline.",
"You avoid structure completely.",
"You escape pressure instead of facing it.",
"You rely on feelings for decisions.",
"You struggle with long-term focus.",
"You avoid difficult situations.",
"You act impulsively without thinking.",
"You prefer comfort over growth.",
"You avoid commitments.",
"You struggle with planning ahead.",
"You rely on emotions over logic.",
"You avoid challenges quietly.",
"You prefer easy paths.",
"You struggle with discipline.",
"You avoid confrontation.",
"You follow instincts blindly.",
"You avoid responsibility.",
"You struggle with direction.",
"You prefer short-term comfort.",
"You avoid structured environments.",
"You rely on emotions for everything.",
"You resist planning."
],
ESTP: [
"You act first and think never.",
"You treat life like a highlight reel.",
"You confuse impulsiveness with confidence.",
"You live in the moment because planning scares you.",
"You take risks without thinking.",
"You prioritize excitement over stability.",
"You act before understanding consequences.",
"You chase thrills constantly.",
"You struggle with long-term thinking.",
"You rely on instinct over logic.",
"You avoid planning entirely.",
"You prefer action over thought.",
"You make decisions impulsively.",
"You ignore consequences.",
"You prioritize fun over responsibility.",
"You struggle with discipline.",
"You act without considering outcomes.",
"You avoid structure.",
"You chase adrenaline constantly.",
"You ignore long-term impact.",
"You prefer immediate rewards.",
"You struggle with consistency.",
"You act without thinking deeply.",
"You prioritize excitement over logic.",
"You avoid responsibility.",
"You act impulsively.",
"You resist planning.",
"You prefer spontaneity always.",
"You ignore details.",
"You act without reflection."
]
};

module.exports = insults;